import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { initProject } from "./init-project.js";

function makeTempDir(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

describe("initProject", () => {
  it("exports boilerplate, generates .env, replaces placeholders, and resets polar ids", () => {
    const sourceDir = makeTempDir("tstack-init-source-");
    const targetDir = join(sourceDir, "../tstack-init-target-" + Date.now());

    try {
      // Set up minimal boilerplate structure
      writeFileSync(join(sourceDir, "README.md"), "# MyApp");
      mkdirSync(join(sourceDir, "src", "features", "billing", "generated"), { recursive: true });
      writeFileSync(
        join(sourceDir, "src", "features", "billing", "generated", "products.generated.ts"),
        "// Generated by eni\nexport const x = 1;",
      );
      mkdirSync(join(sourceDir, "polar"), { recursive: true });
      writeFileSync(
        join(sourceDir, "polar", "products.sandbox.json"),
        JSON.stringify({ products: [{ slug: "pro", polarProductId: "abc", name: "Pro" }] }),
      );
      writeFileSync(
        join(sourceDir, "polar", "meters.sandbox.json"),
        JSON.stringify({ meters: [{ slug: "tokens", polarMeterId: "xyz", name: "Tokens" }] }),
      );
      writeFileSync(
        join(sourceDir, ".env.example"),
        "NEXT_PUBLIC_APP_NAME=MyApp\nDATABASE_URL=postgresql://myapp:myapp-dev-password@localhost:5432/myapp\nBETTER_AUTH_SECRET=\n",
      );
      writeFileSync(join(sourceDir, "package.json"), '{"name": "@tstack/boilerplate"}');

      initProject({
        sourceDir,
        targetDir,
        slug: "acme",
        displayName: "Acme",
        providers: {
          github: true,
          twitter: false,
          walletConnect: false,
          polar: true,
          digitalOcean: false,
          analytics: "umami",
        },
      });

      // Boilerplate copied
      expect(existsSync(join(targetDir, "README.md"))).toBe(true);
      expect(readFileSync(join(targetDir, "README.md"), "utf8")).toBe("# Acme");

      // .env generated
      const envContent = readFileSync(join(targetDir, ".env"), "utf8");
      expect(envContent).toContain("NEXT_PUBLIC_APP_NAME=Acme");
      expect(envContent).toContain("DATABASE_URL=postgresql://acme:acme-dev-password@localhost:5432/acme");
      expect(envContent).toContain("BETTER_AUTH_SECRET=");
      expect(envContent).not.toContain("myapp");
      expect(envContent).not.toContain("MyApp");

      // Package name replaced
      const pkg = JSON.parse(readFileSync(join(targetDir, "package.json"), "utf8"));
      expect(pkg.name).toBe("acme");

      // Polar IDs reset
      const products = JSON.parse(readFileSync(join(targetDir, "polar", "products.sandbox.json"), "utf8"));
      expect(products.products[0].polarProductId).toBeNull();
      const meters = JSON.parse(readFileSync(join(targetDir, "polar", "meters.sandbox.json"), "utf8"));
      expect(meters.meters[0].polarMeterId).toBeNull();

      // Generated header updated
      const generated = readFileSync(
        join(targetDir, "src", "features", "billing", "generated", "products.generated.ts"),
        "utf8",
      );
      expect(generated).toContain("Generated by tstack");
      expect(generated).not.toContain("Generated by eni");
    } finally {
      rmSync(sourceDir, { recursive: true, force: true });
      if (existsSync(targetDir)) rmSync(targetDir, { recursive: true, force: true });
    }
  });

  it("throws when the target directory already exists", () => {
    const sourceDir = makeTempDir("tstack-init-source-");
    const targetDir = makeTempDir("tstack-init-target-");

    try {
      expect(() =>
        initProject({
          sourceDir,
          targetDir,
          slug: "acme",
          displayName: "Acme",
          providers: { github: false, twitter: false, walletConnect: false, polar: false, digitalOcean: false, analytics: "none" },
        }),
      ).toThrow("Target directory already exists");
    } finally {
      rmSync(sourceDir, { recursive: true, force: true });
      rmSync(targetDir, { recursive: true, force: true });
    }
  });
});
