import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { exportBoilerplate } from "./export-boilerplate.js";
import { generateEnv } from "./env.js";
import { buildReplacements, replacePlaceholders } from "./replace.js";
import { resetTemplateIds } from "./reset-template-ids.js";
import { generateSecret } from "./generate-secret.js";
import { setupGit } from "./git.js";
import { installDependencies } from "./install.js";

export interface ProviderConfig {
  github: boolean;
  twitter: boolean;
  walletConnect: boolean;
  polar: boolean;
  digitalOcean: boolean;
  analytics: "umami" | "posthog" | "none";
}

export interface InitProjectOptions {
  sourceDir: string;
  targetDir: string;
  slug: string;
  displayName: string;
  providers: ProviderConfig;
  envOverrides?: Record<string, string>;
  initGit?: boolean;
  installDeps?: boolean;
}

function isTextFile(filePath: string): boolean {
  const textExtensions = new Set([
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".json",
    ".md",
    ".css",
    ".html",
    ".txt",
    ".yml",
    ".yaml",
    ".xml",
    ".svg",
    ".env",
    ".example",
    ".sql",
  ]);
  const ext = filePath.slice(filePath.lastIndexOf("."));
  return textExtensions.has(ext);
}

function replaceInDirectory(dir: string, replacements: Map<string, string>): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const entryPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      replaceInDirectory(entryPath, replacements);
    } else if (entry.isFile() && isTextFile(entryPath)) {
      const content = readFileSync(entryPath, "utf8");
      const updated = replacePlaceholders(content, replacements);
      if (updated !== content) {
        writeFileSync(entryPath, updated);
      }
    }
  }
}

function updateGeneratedHeader(dir: string): void {
  const generatedDir = join(dir, "src", "features", "billing", "generated");
  try {
    const entries = readdirSync(generatedDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isFile() && entry.name.endsWith(".ts")) {
        const path = join(generatedDir, entry.name);
        const content = readFileSync(path, "utf8");
        if (content.includes("Generated by eni")) {
          writeFileSync(path, content.replace(/Generated by eni/g, "Generated by tstack"));
        }
      }
    }
  } catch {
    // generated directory may not exist
  }
}

export function initProject(options: InitProjectOptions): void {
  const { sourceDir, targetDir, slug, displayName, providers, envOverrides, initGit, installDeps } = options;

  exportBoilerplate({ sourceDir, targetDir });

  const replacements = buildReplacements({ slug, displayName });
  replaceInDirectory(targetDir, replacements);

  // Reset Polar IDs
  const polarDir = join(targetDir, "polar");
  try {
    const entries = readdirSync(polarDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile()) continue;
      const path = join(polarDir, entry.name);
      const content = readFileSync(path, "utf8");
      const data = JSON.parse(content) as Record<string, unknown>;
      let updated = data;
      if (entry.name.startsWith("products")) {
        updated = resetTemplateIds(data, "products");
      } else if (entry.name.startsWith("meters")) {
        updated = resetTemplateIds(data, "meters");
      }
      if (JSON.stringify(updated) !== JSON.stringify(data)) {
        writeFileSync(path, JSON.stringify(updated, null, 2) + "\n");
      }
    }
  } catch {
    // polar directory may not exist
  }

  // Generate .env from .env.example
  const envExamplePath = join(targetDir, ".env.example");
  try {
    const exampleContent = readFileSync(envExamplePath, "utf8");
    const envValues: Record<string, string> = {
      NEXT_PUBLIC_APP_NAME: displayName,
      PROJECT_URL: `http://localhost:3000`,
      NEXT_PUBLIC_SITE_URL: `http://localhost:3000`,
      BETTER_AUTH_SECRET: generateSecret(),
      BETTER_AUTH_URL: `http://localhost:3000`,
      DATABASE_URL: `postgresql://${slug}:${slug}-dev-password@localhost:5432/${slug}`,
      NEXT_PUBLIC_ANALYTICS_PROVIDER: providers.analytics,
    };

    if (providers.github) {
      envValues.GITHUB_CLIENT_ID = "";
      envValues.GITHUB_CLIENT_SECRET = "";
    }
    if (providers.twitter) {
      envValues.TWITTER_CLIENT_ID = "";
      envValues.TWITTER_CLIENT_SECRET = "";
    }
    if (providers.walletConnect) {
      envValues.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "";
    }
    if (providers.polar) {
      envValues.POLAR_ACCESS_TOKEN = "";
      envValues.POLAR_SERVER = "sandbox";
      envValues.POLAR_WEBHOOK_SECRET = "";
      envValues.POLAR_ORGANIZATION_ID = "";
    }
    if (providers.digitalOcean) {
      envValues.FILE_UPLOAD_PROVIDER = "digitalocean";
      envValues.DIGITALOCEAN_SPACES_ENDPOINT = "https://ams3.digitaloceanspaces.com";
      envValues.DIGITALOCEAN_SPACES_REGION = "ams3";
    }
    if (providers.analytics === "umami") {
      envValues.NEXT_PUBLIC_UMAMI_WEBSITE_ID = "";
      envValues.NEXT_PUBLIC_UMAMI_HOST = "https://cloud.umami.is";
    }
    if (providers.analytics === "posthog") {
      envValues.NEXT_PUBLIC_POSTHOG_KEY = "";
      envValues.NEXT_PUBLIC_POSTHOG_HOST = "https://eu.posthog.com";
    }

    // Apply user-provided overrides (only non-empty values)
    if (envOverrides) {
      for (const [key, value] of Object.entries(envOverrides)) {
        if (value) {
          envValues[key] = value;
        }
      }
    }

    const envContent = generateEnv({ exampleContent, values: envValues });
    writeFileSync(join(targetDir, ".env"), envContent + "\n");
  } catch {
    // .env.example may not exist
  }

  updateGeneratedHeader(targetDir);

  if (initGit) {
    setupGit(targetDir);
  }

  if (installDeps) {
    installDependencies(targetDir);
  }
}
