import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export interface Meter {
  slug: string;
  name: string;
  polarMeterId: string | null;
  eventNames: string[];
}

const KEBAB_CASE_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
const METER_KEYS = new Set(["slug", "name", "polarMeterId", "eventNames"]);

function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

export function validateMeter(meter: unknown): string[] {
  const errors: string[] = [];
  const m = meter as Record<string, unknown>;

  for (const key of Object.keys(m)) {
    if (!METER_KEYS.has(key)) {
      errors.push(`unexpected field: ${key}`);
    }
  }

  if (!m.slug || typeof m.slug !== "string") {
    errors.push("slug is required");
  } else if (!KEBAB_CASE_RE.test(m.slug)) {
    errors.push("slug must be kebab-case");
  }

  if (!m.name || typeof m.name !== "string") {
    errors.push("name is required");
  }

  if (!(m.polarMeterId === null || typeof m.polarMeterId === "string")) {
    errors.push("polarMeterId must be a string or null");
  }

  if (!Array.isArray(m.eventNames) || m.eventNames.length === 0) {
    errors.push("eventNames must have at least one entry");
  } else if (m.eventNames.some((eventName) => typeof eventName !== "string")) {
    errors.push("eventNames must contain only strings");
  }

  return errors;
}

export function readMeters(filePath: string): Meter[] {
  const content = readFileSync(filePath, "utf8");
  const data = JSON.parse(content) as { meters?: unknown };

  if (!Array.isArray(data.meters)) {
    throw new Error(`${filePath} must contain a meters array`);
  }

  const errors = data.meters.flatMap((meter, index) =>
    validateMeter(meter).map((error) => `meters[${index}]: ${error}`),
  );

  if (errors.length > 0) {
    throw new Error(`Invalid meter configuration in ${filePath}:\n${errors.join("\n")}`);
  }

  return data.meters as Meter[];
}

function meterToObjectLiteral(meter: Meter): string {
  const lines: string[] = [];
  lines.push("  {");
  lines.push(`    slug: "${escapeString(meter.slug)}",`);
  lines.push(`    name: "${escapeString(meter.name)}",`);
  lines.push(`    polarMeterId: ${meter.polarMeterId != null ? `"${escapeString(meter.polarMeterId)}"` : "null"},`);
  lines.push(`    eventNames: [${meter.eventNames.map((eventName) => `"${escapeString(eventName)}"`).join(",")}],`);
  lines.push("  }");
  return lines.join("\n");
}

export function generateMetersTypeScript(options: {
  sandboxMeters: Meter[];
  productionMeters: Meter[];
  header?: string;
}): string {
  const { sandboxMeters, productionMeters, header = "Generated by tstack" } = options;

  const parts: string[] = [];
  parts.push("// AUTO-GENERATED - DO NOT EDIT");
  parts.push(`// ${header}`);
  parts.push("");
  parts.push("export interface GeneratedMeter {");
  parts.push("  slug: string;");
  parts.push("  name: string;");
  parts.push("  polarMeterId: string | null;");
  parts.push("  eventNames: readonly string[];");
  parts.push("}");
  parts.push("");
  parts.push("export const sandboxMeters = [");
  parts.push(sandboxMeters.map(meterToObjectLiteral).join(",\n"));
  parts.push("] as const satisfies readonly GeneratedMeter[];");
  parts.push("");
  parts.push("export const productionMeters = [");
  parts.push(productionMeters.map(meterToObjectLiteral).join(",\n"));
  parts.push("] as const satisfies readonly GeneratedMeter[];");
  parts.push("");
  parts.push("export type MeterSlug =");
  parts.push("  | (typeof sandboxMeters)[number][\"slug\"]");
  parts.push("  | (typeof productionMeters)[number][\"slug\"];");
  parts.push("");
  parts.push("export type MeterEventNames<S extends MeterSlug> = Extract<");
  parts.push("  (typeof sandboxMeters)[number] | (typeof productionMeters)[number],");
  parts.push("  { slug: S }");
  parts.push(">[\"eventNames\"][number];");
  parts.push("");
  parts.push("export function getMeters(env: \"sandbox\" | \"production\"): readonly GeneratedMeter[] {");
  parts.push("  return env === \"sandbox\" ? sandboxMeters : productionMeters;");
  parts.push("}");
  parts.push("");
  parts.push("export function getMeter(");
  parts.push("  env: \"sandbox\" | \"production\",");
  parts.push("  slug: MeterSlug,");
  parts.push("): GeneratedMeter | undefined {");
  parts.push("  return getMeters(env).find((m) => m.slug === slug);");
  parts.push("}");
  parts.push("");
  parts.push("/**");
  parts.push(" * Resolves an event name to a human-readable meter display name.");
  parts.push(" * Falls back to the raw event name if no matching meter is found.");
  parts.push(" */");
  parts.push("export function resolveEventDisplayName(");
  parts.push("  env: \"sandbox\" | \"production\",");
  parts.push("  eventName: string,");
  parts.push("): string {");
  parts.push("  const meters = getMeters(env);");
  parts.push("  const meter = meters.find((m) => m.eventNames.includes(eventName));");
  parts.push("  return meter?.name ?? eventName;");
  parts.push("}");
  parts.push("");

  return parts.join("\n");
}

export function writeMetersGenerated(options: {
  projectDir: string;
  sandboxMeters: Meter[];
  productionMeters: Meter[];
}): void {
  const { projectDir, sandboxMeters, productionMeters } = options;
  const generatedDir = join(resolve(projectDir), "src", "features", "billing", "generated");
  mkdirSync(generatedDir, { recursive: true });
  const content = generateMetersTypeScript({ sandboxMeters, productionMeters });
  writeFileSync(join(generatedDir, "meters.generated.ts"), content);
}
