import { describe, expect, it } from "vitest";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  generateMetersTypeScript,
  readMeters,
  validateMeter,
  writeMetersGenerated,
} from "./meters.js";

function makeTempDir(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

describe("readMeters", () => {
  it("reads meters from a JSON file with wrapper", () => {
    const dir = makeTempDir("tstack-meters-");
    const filePath = join(dir, "meters.sandbox.json");

    try {
      writeFileSync(
        filePath,
        JSON.stringify({
          $schema: "./meters.schema.json",
          meters: [
            {
              slug: "llm-tokens",
              name: "LLM Tokens",
              polarMeterId: "meter-123",
              eventNames: ["use-credit"],
            },
          ],
        }),
      );

      const meters = readMeters(filePath);
      expect(meters).toHaveLength(1);
      expect(meters[0]).toMatchObject({ slug: "llm-tokens", name: "LLM Tokens" });
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("validateMeter", () => {
  const validMeter = {
    slug: "llm-tokens",
    name: "LLM Tokens",
    polarMeterId: null,
    eventNames: ["use-credit"],
  };

  it("returns no errors for a valid meter", () => {
    expect(validateMeter(validMeter)).toEqual([]);
  });

  it("returns errors for missing required fields", () => {
    expect(validateMeter({ ...validMeter, slug: undefined })).toContain("slug is required");
    expect(validateMeter({ ...validMeter, name: "" })).toContain("name is required");
    expect(validateMeter({ ...validMeter, eventNames: [] })).toContain("eventNames must have at least one entry");
  });

  it("returns errors for invalid field shapes", () => {
    expect(validateMeter({ ...validMeter, slug: "LLM Tokens" })).toContain("slug must be kebab-case");
    expect(validateMeter({ ...validMeter, polarMeterId: 123 })).toContain("polarMeterId must be a string or null");
    expect(validateMeter({ ...validMeter, eventNames: ["use-credit", 12] })).toContain("eventNames must contain only strings");
  });

  it("returns errors for fields outside the meter schema", () => {
    expect(validateMeter({ ...validMeter, extra: true })).toContain("unexpected field: extra");
  });
});

describe("generateMetersTypeScript", () => {
  const sandboxMeters = [
    {
      slug: "llm-tokens",
      name: "LLM Tokens",
      polarMeterId: "meter-123",
      eventNames: ["use-credit"],
    },
  ];

  const productionMeters = [
    {
      slug: "llm-tokens",
      name: "LLM Tokens",
      polarMeterId: null,
      eventNames: ["use-credit"],
    },
  ];

  it("preserves the runtime meter exports", () => {
    const ts = generateMetersTypeScript({ sandboxMeters, productionMeters });

    expect(ts).toContain("export interface GeneratedMeter");
    expect(ts).toContain("export const sandboxMeters");
    expect(ts).toContain("export const productionMeters");
    expect(ts).toContain("export type MeterSlug");
    expect(ts).toContain("export type MeterEventNames");
    expect(ts).toContain('export function getMeters(env: "sandbox" | "production")');
    expect(ts).toContain("export function getMeter(");
    expect(ts).toContain("export function resolveEventDisplayName(");
  });

  it("includes meter ids, null ids, and event names from both environments", () => {
    const ts = generateMetersTypeScript({ sandboxMeters, productionMeters });

    expect(ts).toContain('polarMeterId: "meter-123"');
    expect(ts).toContain("polarMeterId: null");
    expect(ts).toContain('eventNames: ["use-credit"]');
    expect(ts).toContain("Generated by tstack");
  });
});

describe("writeMetersGenerated", () => {
  it("writes meters.generated.ts to the billing generated directory", () => {
    const dir = makeTempDir("tstack-meters-generated-");
    const generatedDir = join(dir, "src", "features", "billing", "generated");

    try {
      writeMetersGenerated({
        projectDir: dir,
        sandboxMeters: [
          {
            slug: "llm-tokens",
            name: "LLM Tokens",
            polarMeterId: "meter-123",
            eventNames: ["use-credit"],
          },
        ],
        productionMeters: [
          {
            slug: "llm-tokens",
            name: "LLM Tokens",
            polarMeterId: null,
            eventNames: ["use-credit"],
          },
        ],
      });

      const filePath = join(generatedDir, "meters.generated.ts");
      expect(existsSync(filePath)).toBe(true);
      const content = readFileSync(filePath, "utf8");
      expect(content).toContain("Generated by tstack");
      expect(content).toContain('polarMeterId: "meter-123"');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
