import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export interface ProductPrice {
  amountType: "fixed" | "custom" | "free";
  amount?: number;
  currency?: string;
  minimumAmount?: number;
  maximumAmount?: number;
  presetAmount?: number;
}

export interface ProductDisplay {
  title: string;
  subtitle?: string;
  badge: string | null;
  features: string[];
  highlighted: boolean;
  cta: string;
}

export interface Product {
  slug: string;
  name: string;
  description?: string;
  type: "subscription" | "one_time" | "free";
  recurringInterval?: "day" | "week" | "month" | "year";
  recurringIntervalCount?: number;
  prices: ProductPrice[];
  display: ProductDisplay;
  polarProductId?: string | null;
}

export function readProducts(filePath: string): Product[] {
  const content = readFileSync(filePath, "utf8");
  const data = JSON.parse(content) as { products: Product[] };
  return data.products;
}

export function writeProducts(filePath: string, products: Product[], schemaPath?: string): void {
  let existingSchema: string | undefined;
  try {
    const existing = JSON.parse(readFileSync(filePath, "utf8")) as { $schema?: string };
    existingSchema = existing.$schema;
  } catch {
    // file may not exist
  }

  const data = {
    $schema: existingSchema ?? schemaPath ?? "./products.schema.json",
    products,
  };

  writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n");
}

const KEBAB_CASE_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

function periodForType(type: Product["type"], interval?: string): string | undefined {
  if (type === "free") return undefined;
  if (type === "one_time") return undefined;
  if (interval === "month") return "/month";
  if (interval === "year") return "/year";
  if (interval === "day") return "/day";
  if (interval === "week") return "/week";
  return undefined;
}

function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function productToObjectLiteral(product: Product): string {
  const display = product.display;
  const price = formatPrice(product.prices[0] ?? { amountType: "free" });
  const period = periodForType(product.type, product.recurringInterval);

  const lines: string[] = [];
  lines.push(`  {`);
  lines.push(`    slug: "${escapeString(product.slug)}",`);
  lines.push(`    productId: ${product.polarProductId != null ? `"${escapeString(product.polarProductId)}"` : "null"},`);
  lines.push(`    name: "${escapeString(product.name)}",`);
  lines.push(`    type: "${product.type}",`);
  lines.push(`    display: {`);
  lines.push(`      title: "${escapeString(display.title)}",`);
  if (display.subtitle) {
    lines.push(`      subtitle: "${escapeString(display.subtitle)}",`);
  }
  lines.push(`      price: "${escapeString(price)}",`);
  if (period !== undefined) {
    lines.push(`      period: "${escapeString(period)}",`);
  }
  lines.push(`      badge: ${display.badge != null ? `"${escapeString(display.badge)}"` : "null"},`);
  lines.push(`      features: [${display.features.map((f) => `"${escapeString(f)}"`).join(",")}],`);
  lines.push(`      highlighted: ${display.highlighted},`);
  lines.push(`      cta: "${escapeString(display.cta)}",`);
  lines.push(`    },`);
  lines.push(`  }`);
  return lines.join("\n");
}

export function generateProductsTypeScript(options: {
  sandboxProducts: Product[];
  productionProducts: Product[];
  header?: string;
}): string {
  const { sandboxProducts, productionProducts, header = "Generated by tstack" } = options;

  const parts: string[] = [];
  parts.push("// AUTO-GENERATED - DO NOT EDIT");
  parts.push(`// ${header}`);
  parts.push("");
  parts.push("export interface ProductDisplay {");
  parts.push("  title: string;");
  parts.push("  subtitle?: string;");
  parts.push("  price: string;");
  parts.push("  period?: string;");
  parts.push("  badge: string | null;");
  parts.push("  features: string[];");
  parts.push("  highlighted: boolean;");
  parts.push("  cta: string;");
  parts.push("}");
  parts.push("");
  parts.push("export interface GeneratedProduct {");
  parts.push("  slug: string;");
  parts.push("  productId: string | null;");
  parts.push("  name: string;");
  parts.push('  type: "subscription" | "one_time" | "free";');
  parts.push("  display: ProductDisplay;");
  parts.push("}");
  parts.push("");

  parts.push("export const sandboxProducts: GeneratedProduct[] = [");
  parts.push(sandboxProducts.map(productToObjectLiteral).join(",\n"));
  parts.push("] as const;");
  parts.push("");

  parts.push("export const productionProducts: GeneratedProduct[] = [");
  parts.push(productionProducts.map(productToObjectLiteral).join(",\n"));
  parts.push("] as const;");
  parts.push("");

  parts.push('export function getProducts(env: "sandbox" | "production"): GeneratedProduct[] {');
  parts.push("  return env === \"sandbox\" ? sandboxProducts : productionProducts;");
  parts.push("}");
  parts.push("");
  parts.push("/**");
  parts.push(" * BetterAuth checkout products format");
  parts.push(" * Only includes products with a valid polarProductId");
  parts.push(" */");
  parts.push("export function getCheckoutProducts(env: \"sandbox\" | \"production\") {");
  parts.push("  return getProducts(env)");
  parts.push("    .filter((p) => p.productId !== null)");
  parts.push("    .map((p) => ({");
  parts.push("      productId: p.productId as string,");
  parts.push("      slug: p.slug,");
  parts.push("    }));");
  parts.push("}");
  parts.push("");
  parts.push("/**");
  parts.push(" * Get products formatted for pricing page display");
  parts.push(" * Only includes products intended for display (with valid features)");
  parts.push(" */");
  parts.push("export function getDisplayProducts(env: \"sandbox\" | \"production\") {");
  parts.push("  return getProducts(env).filter((p) => p.display.features.length > 0);");
  parts.push("}");
  parts.push("");

  return parts.join("\n");
}

export function writeProductsGenerated(options: {
  projectDir: string;
  sandboxProducts: Product[];
  productionProducts: Product[];
}): void {
  const { projectDir, sandboxProducts, productionProducts } = options;
  const generatedDir = join(resolve(projectDir), "src", "features", "billing", "generated");
  mkdirSync(generatedDir, { recursive: true });
  const content = generateProductsTypeScript({ sandboxProducts, productionProducts });
  writeFileSync(join(generatedDir, "products.generated.ts"), content);
}

export function generateYearlyProduct(monthlyProduct: Product): Product {
  const slug = monthlyProduct.slug.replace(/-monthly$/, "") + "-yearly";
  const name = monthlyProduct.name.replace(/ Monthly$/, " Yearly");
  const description = monthlyProduct.description
    ? monthlyProduct.description.replace(/monthly/gi, "yearly")
    : undefined;

  const monthlyAmount = monthlyProduct.prices[0]?.amount ?? 0;
  const yearlyAmount = monthlyAmount * 10;

  return {
    slug,
    name,
    description,
    type: "subscription",
    recurringInterval: "year",
    recurringIntervalCount: 1,
    prices: [
      {
        amountType: "fixed",
        amount: yearlyAmount,
        currency: monthlyProduct.prices[0]?.currency ?? "usd",
      },
    ],
    display: {
      title: monthlyProduct.display.title,
      subtitle: "Billed yearly",
      badge: "2 months free",
      features: monthlyProduct.display.features,
      highlighted: monthlyProduct.display.highlighted,
      cta: monthlyProduct.display.cta,
    },
    polarProductId: null,
  };
}

function formatDollars(cents: number): string {
  const dollars = Math.floor(cents / 100);
  const remainder = cents % 100;
  if (remainder === 0) return `$${dollars}`;
  return `$${dollars}.${remainder.toString().padStart(2, "0")}`;
}

export function formatPrice(price: ProductPrice): string {
  if (price.amountType === "free") return "Free";
  if (price.amountType === "custom") {
    if (price.presetAmount != null) {
      return formatDollars(price.presetAmount);
    }
    return "Custom";
  }
  if (price.amount != null) {
    return formatDollars(price.amount);
  }
  return "";
}

export function validateProduct(product: unknown): string[] {
  const errors: string[] = [];
  const p = product as Record<string, unknown>;

  if (!p.slug || typeof p.slug !== "string") {
    errors.push("slug is required");
  } else if (!KEBAB_CASE_RE.test(p.slug)) {
    errors.push("slug must be kebab-case");
  }

  if (!p.name || typeof p.name !== "string") {
    errors.push("name is required");
  }

  const type = p.type;
  if (!type || !["subscription", "one_time", "free"].includes(type as string)) {
    errors.push('type must be "subscription", "one_time", or "free"');
  }

  if (type === "subscription") {
    const interval = p.recurringInterval;
    if (!interval || !["day", "week", "month", "year"].includes(interval as string)) {
      errors.push("recurringInterval is required for subscriptions");
    }
  }

  const prices = Array.isArray(p.prices) ? p.prices : [];
  if (prices.length === 0) {
    errors.push("prices must have at least one entry");
  }

  const display = p.display as Record<string, unknown> | undefined;
  if (!display || typeof display !== "object") {
    errors.push("display is required");
  } else {
    if (!display.title || typeof display.title !== "string" || display.title.length === 0) {
      errors.push("display.title is required");
    }
    if (!Array.isArray(display.features)) {
      errors.push("display.features must be an array");
    }
    if (typeof display.highlighted !== "boolean") {
      errors.push("display.highlighted must be a boolean");
    }
    if (!display.cta || typeof display.cta !== "string" || display.cta.length === 0) {
      errors.push("display.cta is required");
    }
  }

  return errors;
}
